export const ATTEMPTS_TO_COMPLETE_GUY_DRAWING = 7;
export const ATTEMPTS_TO_COMPLETE_TREE_DRAWING = 3;
export const ATTEMPTS_TO_COMPLETE_DRAWING =
  ATTEMPTS_TO_COMPLETE_GUY_DRAWING + ATTEMPTS_TO_COMPLETE_TREE_DRAWING;
